name: Build native program to run on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GraalVM
      uses: actions/setup-java@v2
      with:
        distribution: 'graalvm'
        java-version: '21.0.0' # Use the latest version of GraalVM

    - name: Install Native Image
      run: gu install native-image

    - name: Compile Java program to native executable
      run: native-image -cp . Main

    - name: Upload native executable
      uses: actions/upload-artifact@v2
      with:
        name: native-executable
        path: Main.exe
